title: Michael’s Musings
author: Michael Salmon
email: msalmonse@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Random musings on subjects that interest me.

theme: minima

# social links
twitter_username: msalmonse
github_username:  msalmonse

show_excerpts: true # set to false to remove excerpts on the homepage
